SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Logger]'
GO
ALTER TABLE [dbo].[Logger] DROP CONSTRAINT [LoggerPK]
GO
PRINT N'Dropping constraints from [dbo].[Logger]'
GO
ALTER TABLE [dbo].[Logger] DROP CONSTRAINT [DF__Logger__LogDate__02FC7413]
GO
PRINT N'Dropping [dbo].[Logger]'
GO
DROP TABLE [dbo].[Logger]
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

