SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Suppliers]'
GO
ALTER TABLE [dbo].[Suppliers] DROP CONSTRAINT [PK_Suppliers]
GO
PRINT N'Dropping index [CompanyName] from [dbo].[Suppliers]'
GO
DROP INDEX [CompanyName] ON [dbo].[Suppliers]
GO
PRINT N'Dropping index [PostalCode] from [dbo].[Suppliers]'
GO
DROP INDEX [PostalCode] ON [dbo].[Suppliers]
GO
PRINT N'Dropping [dbo].[Suppliers]'
GO
DROP TABLE [dbo].[Suppliers]
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

