SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Logger]'
GO
CREATE TABLE [dbo].[Logger]
(
[LogID] [int] NOT NULL,
[LogDate] [datetime] NULL CONSTRAINT [DF__Logger__LogDate__02FC7413] DEFAULT (sysutcdatetime()),
[LogMsg] [varchar] (2000) NULL
)
GO
PRINT N'Creating primary key [LoggerPK] on [dbo].[Logger]'
GO
ALTER TABLE [dbo].[Logger] ADD CONSTRAINT [LoggerPK] PRIMARY KEY CLUSTERED ([LogID])
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

